
<div id ='Modal-add' class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Add new User</h4>
      </div>
      <form method="post" id="surveyForm" action ='<?= $this->url('user', array('action'=>'save'));?>' class="form-horizontal">
      <div class="modal-body">  
        <div class="form-group">
            <label class="col-xs-3 control-label">Full name</label>
            <div class="col-xs-5">
                <input type="text" class="form-control" name="fullname" />
            </div>
        </div>    
        <div class="form-group">
            <label class="col-xs-3 control-label">Phone Number</label>
            <div class="col-xs-5">
                <input type="text" class="form-control" name="phoneNumber[]" />
                <input type="hidden" class="form-control" name="ids[]" />
            </div>
            <div class="col-xs-4">
                <button type="button" class="btn btn-default addButton">+</button>
            </div>
        </div>
        <div class="form-group hide" id="optionTemplate">
            <div class="col-xs-offset-3 col-xs-5">
                <input class="form-control" type="text" name="phoneNumber[]" />
                <input type="hidden" class="form-control" name="ids[]" />
            </div>
            <div class="col-xs-4">
                <button type="button" class="btn btn-default removeButton">-</button>
            </div>
        </div>

      </div>
      <div class="modal-footer">
        <input type="submit" class="btn btn-default" value="Submit">
      </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->