
<div id ='Modal-add' class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Add new User</h4>
      </div>
      <form method="post" action ='<?= $this->url('user', array('action'=>'add'));?>'>
      <div class="modal-body">       
        Full name: <input type="text" name="fullname">
      </div>
      <div class="modal-footer">
        <input type="submit" class="btn btn-default" value="Submit">
      </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->