<div id ='myModal' class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete User</h4>
      </div>
      <div class="modal-body">
        Are you sure you want to delete user <?= $user->getFullname(); ?>? <br/> 
      </div>
      <div class="modal-footer">
         <form method="post" action='<?= $this->url('user', array('action'=>'delete', 'id' => $user->getId()));?>'>
          <input type="submit" class="btn btn-default" value="Delete">
         </form>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->