<div id ='Modal-edit' class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Edit User</h4>
      </div>
      <form method="post" action='<?= $this->url('user', array('action'=>'edit', 'id' => $user->getId()));?>'>
          <div class="modal-body">       
              fullname: <input type="text" name="fullname" value="<?php echo $user->getFullname(); ?>">
          </div>
          <div class="modal-footer">
            <input type="submit" class="btn btn-default" value="Validate">
          </div>
       </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->