<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Users</h3>
            </div>
            <div class="panel-body">
                <a data-toggle="modal" data-target="#Modal-add" href="#">Add User</a>

                <?php if (isset($users)) : ?>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Full name</th>
                        <th>Phone Numbers</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                <?php foreach($users as $user): ?>
                    <tbody>
                    <tr>
                        <td><?= $user->getId(); ?></td>
                        <td><?= $user->getFullName(); ?></td>
                        <td><?php foreach ($user->getPhonenumbers() as $element) {
                           echo ' ' . $element->getNumber(); 
                        }?></td>
                        <td>
                            <a data-toggle="modal" data-target="#Modal-edit" href="#">Edit</a> |
                            <a data-toggle="modal" data-target="#myModal" href="#">Delete</a>
                            <?= $this->partial('edit.phtml',['user' => $user])?>
                            <?= $this->partial('delete.phtml',['user' => $user])?>
                        </td>
                    </tr>
                    </tbody>
                <?php endforeach; ?>
                </table>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?= $this->partial('add.phtml')?>
